name: Deploy to cloud functions

on:
  push:
    branches: main

jobs:
  deploy-to-cloud-functions:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

      - uses: google-github-actions/deploy-cloud-functions@v3
        timeout-minutes: 10
        with:
          name: interiorize-function
          runtime: nodejs20
          source_dir: src
          entry_point: api
          environment_variables: |-
            DB_HOST=${{ secrets.DB_HOST }}
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            JWKSURI=${{ secrets.AUTH0_ISSUER }}/.well-known/jwks.json
            ISSUER=${{ secrets.AUTH0_ISSUER }}/
