name: Deploy to cloud functions

on:
  push:
    branches: "test-gha"

env:
  PROJECT_PREFIX: projects/titanium-spider-428214-u0/secrets

jobs:
  deploy-to-cloud-functions:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

      - uses: google-github-actions/deploy-cloud-functions@v2
        timeout-minutes: 10
        with:
          name: interiorize-function
          runtime: nodejs20
          source_dir: src
          entry_point: api
          secret_environment_variables: |-
            DB_HOST=${{ env.PROJECT_PREFIX }}/interiorize-db-host
            DB_NAME=${{ env.PROJECT_PREFIX }}/interiorize-db-name
            DB_USER=${{ env.PROJECT_PREFIX }}/interiorize-db-user
            JWKSURI=${{ env.PROJECT_PREFIX }}/interiorize-auth0-jwks-uri
            ISSUER=${{ env.PROJECT_PREFIX }}/interiorize-auth0-issuer
